services:
  omero-db:
    image: postgres:16
    environment:
      POSTGRES_DB: omero
      POSTGRES_USER: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero-net
    volumes:
      - omero-db-data:/var/lib/postgresql/data

  omero-server:
    image: openmicroscopy/omero-server:latest
    depends_on:
      - omero-db
    environment:
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      CONFIG_omero_db_host: omero-db
      ROOTPASS: omero
      # Create a public user for read-only access
      CONFIG_omero_web_public_enabled: "true"
      CONFIG_omero_web_public_user: "public"
      CONFIG_omero_web_public_password: "public"
    networks:
      - omero-net
    volumes:
      - ./omero-data:/OMERO
    ports:
      - "4064:4064"   # <-- Expose OMERO Insight / API port

  omero-web:
    image: openmicroscopy/omero-web-standalone:latest
    depends_on:
      - omero-server
    environment:
      OMEROHOST: omero-server
      # Enable public user for login-free read access
      CONFIG_omero_web_public_enabled: "true"
      CONFIG_omero_web_public_user: "public"
      CONFIG_omero_web_public_password: "public"
      CONFIG_omero_web_public_server: "1"
      # Allow access to webgateway, webclient, and iviewer without login
      CONFIG_omero_web_public_url__filter: ".*"
    ports:
      - "4080:4080"
    networks:
      - omero-net

  iscc-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - omero-server
    environment:
      OMERO_ISCC_HOST: omero-server
      OMERO_ISCC_PORT: 4064
      OMERO_ISCC_USERNAME: root
      OMERO_ISCC_PASSWORD: omero
      OMERO_ISCC_POLL_INTERVAL: 5
      OMERO_ISCC_BATCH_SIZE: 100
      OMERO_ISCC_NAMESPACE: org.iscc.omero.sum
      OMERO_ISCC_LOG_LEVEL: debug
    restart: unless-stopped
    networks:
      - omero-net
    volumes:
      - ./logs:/app/logs

networks:
  omero-net:

volumes:
  omero-db-data:
